excluded:
    - ../OneMorePlanet/Resources/
    - ../Pods
disabled_rules:
    - trailing_comma
    - trailing_whitespace
    - identifier_name
    - shorthand_operator
    - force_cast
opt_in_rules:
    - yoda_condition
    - unused_import
    - unused_declaration
    - unavailable_function
    - empty_string
    - file_name_no_space
    - weak_delegate
line_length:
  warning: 150
  error: 300
