excluded:
    - ../App/OneMorePlanet/Resources/
    - ../App/Pods
disabled_rules:
    - trailing_comma
    - trailing_whitespace
    - identifier_name
    - shorthand_operator
    - force_cast
opt_in_rules:
    - yoda_condition
    - unused_import
    - unused_declaration
    - unavailable_function
    - empty_string
    - file_name_no_space
line_length:
  error: 300
