input_dir: ../OneMorePlanet/Resources/
output_dir: ../OneMorePlanet/Resources/Generated/
strings:
  - inputs: Strings.strings
    outputs:
      - templateName: structured-swift5
        output: Strings.swift
        params:
          enumName: Strings
xcassets:
  - inputs: Assets.xcassets
    outputs:
      templateName: swift5
      output: Assets.swift
      params:
        enumName: Assets
  - inputs: StarAssets.xcassets
    outputs:
      templateName: swift5
      output: StarAssets.swift
      params:
        enumName: StarAssets
        imageTypeName: StarImageAsset
        imageAliasName: StarAssetImageTypeAlias
        allValues: true
  - inputs: PlanetAssets.xcassets
    outputs:
      templateName: swift5
      output: PlanetAssets.swift
      params:
        enumName: PlanetAssets
        imageTypeName: PlanetImageAsset
        imageAliasName: PlanetAssetImageTypeAlias
        allValues: true
fonts:
  inputs: Fonts
  outputs:
    - templateName: swift5
      output: Fonts.swift
      params:
          enumName: Fonts
